"""is_active

Revision ID: 9c72b6f904f6
Revises: 8d3c85f85964
Create Date: 2025-01-17 22:15:38.066829

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9c72b6f904f6"
down_revision = "8d3c85f85964"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("merchants_integrations", schema=None) as batch_op:
        batch_op.add_column(sa.Column("is_active", sa.Boolean(), default="1"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("merchants_integrations", schema=None) as batch_op:
        batch_op.drop_column("is_active")

    # ### end Alembic commands ###
