"""settings delete

Revision ID: 3d1fa949e7d8
Revises: 4c08a28588e8
Create Date: 2025-11-30 00:23:16.500337

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = "3d1fa949e7d8"
down_revision = "4c08a28588e8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("store_settings")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "store_settings",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("user_id", sa.INTEGER(), nullable=True),
        sa.Column("slug", sa.VARCHAR(length=255), nullable=False),
        sa.Column("active", sa.BOOLEAN(), nullable=False),
        sa.Column("value", sqlite.JSON(), nullable=True),
        sa.Column("created", sa.DATETIME(), nullable=False),
        sa.Column("updated", sa.DATETIME(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], name=op.f("fk_store_settings_user_id_user")),
        sa.PrimaryKeyConstraint("id", "user_id", name=op.f("pk_store_settings")),
        sa.UniqueConstraint("slug", name=op.f("uq_store_settings_slug")),
    )
    # ### end Alembic commands ###
