"""init

Revision ID: bd84710a1598
Revises:
Create Date: 2025-11-14 04:09:42.063609

"""

import flask_security
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "bd84710a1598"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "merchants_integrations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("integration_class", sa.String(length=255), nullable=True),
        sa.Column("config", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_merchants_integrations")),
        sa.UniqueConstraint("slug", name=op.f("uq_merchants_integrations_slug")),
    )
    op.create_table(
        "merchants_payment",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("merchants_token", sa.String(length=255), nullable=False),
        sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column(
            "status",
            sa.Enum("created", "processing", "declined", "cancelled", "refunded", "paid", name="paymentstatus"),
            nullable=False,
        ),
        sa.Column("integration_slug", sa.String(length=255), nullable=False),
        sa.Column("integration_transaction", sa.String(length=255), nullable=True),
        sa.Column("integration_payload", sa.JSON(), nullable=True),
        sa.Column("integration_response", sa.JSON(), nullable=True),
        sa.Column(
            "creation", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "last_update", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_merchants_payment")),
        sa.UniqueConstraint("merchants_token", name=op.f("uq_merchants_payment_merchants_token")),
    )
    with op.batch_alter_table("merchants_payment", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_merchants_payment_integration_slug"), ["integration_slug"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_merchants_payment_integration_transaction"), ["integration_transaction"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_merchants_payment_status"), ["status"], unique=False)

    op.create_table(
        "role",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("permissions", flask_security.datastore.AsaList(), nullable=True),
        sa.Column("update_datetime", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_role")),
        sa.UniqueConstraint("name", name=op.f("uq_role_name")),
    )
    op.create_table(
        "store_category",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("updated", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_store_category")),
        sa.UniqueConstraint("slug", name=op.f("uq_store_category_slug")),
    )
    op.create_table(
        "store_product_type",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("updated", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_store_product_type")),
        sa.UniqueConstraint("slug", name=op.f("uq_store_product_type_slug")),
    )
    op.create_table(
        "user",
        sa.Column("fs_webauthn_user_handle", sa.String(length=64), nullable=True),
        sa.Column("mf_recovery_codes", flask_security.datastore.AsaList(), nullable=True),
        sa.Column("password", sa.String(length=255), nullable=True),
        sa.Column("us_phone_number", sa.String(length=128), nullable=True),
        sa.Column("username", sa.String(length=255), nullable=True),
        sa.Column("us_totp_secrets", sa.Text(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("fs_uniquifier", sa.String(length=64), nullable=False),
        sa.Column("confirmed_at", sa.DateTime(), nullable=True),
        sa.Column("last_login_at", sa.DateTime(), nullable=True),
        sa.Column("current_login_at", sa.DateTime(), nullable=True),
        sa.Column("last_login_ip", sa.String(length=64), nullable=True),
        sa.Column("current_login_ip", sa.String(length=64), nullable=True),
        sa.Column("login_count", sa.Integer(), nullable=True),
        sa.Column("tf_primary_method", sa.String(length=64), nullable=True),
        sa.Column("tf_totp_secret", sa.String(length=255), nullable=True),
        sa.Column("tf_phone_number", sa.String(length=128), nullable=True),
        sa.Column("create_datetime", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.Column("update_datetime", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user")),
        sa.UniqueConstraint("email", name=op.f("uq_user_email")),
        sa.UniqueConstraint("fs_uniquifier", name=op.f("uq_user_fs_uniquifier")),
        sa.UniqueConstraint("fs_webauthn_user_handle", name=op.f("uq_user_fs_webauthn_user_handle")),
        sa.UniqueConstraint("us_phone_number", name=op.f("uq_user_us_phone_number")),
        sa.UniqueConstraint("username", name=op.f("uq_user_username")),
    )
    op.create_table(
        "roles_users",
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("role_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["role_id"], ["role.id"], name=op.f("fk_roles_users_role_id_role")),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], name=op.f("fk_roles_users_user_id_user")),
    )
    op.create_table(
        "store_branch",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("extra_attrs", sa.JSON(), nullable=True),
        sa.Column("partner_id", sa.Integer(), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("updated", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["partner_id"], ["user.id"], name=op.f("fk_store_branch_partner_id_user")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_store_branch")),
        sa.UniqueConstraint("slug", name=op.f("uq_store_branch_slug")),
    )
    with op.batch_alter_table("store_branch", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_store_branch_partner_id"), ["partner_id"], unique=False)

    op.create_table(
        "store_product",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=2048), nullable=True),
        sa.Column("price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("extra_attrs", sa.JSON(), nullable=True),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("product_type_id", sa.Integer(), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("updated", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"], ["store_category.id"], name=op.f("fk_store_product_category_id_store_category")
        ),
        sa.ForeignKeyConstraint(
            ["product_type_id"],
            ["store_product_type.id"],
            name=op.f("fk_store_product_product_type_id_store_product_type"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_store_product")),
        sa.UniqueConstraint("slug", name=op.f("uq_store_product_slug")),
    )
    with op.batch_alter_table("store_product", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_store_product_category_id"), ["category_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_store_product_product_type_id"), ["product_type_id"], unique=False)

    op.create_table(
        "store_branch_product",
        sa.Column("branch_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("price_override", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["branch_id"], ["store_branch.id"], name=op.f("fk_store_branch_product_branch_id_store_branch")
        ),
        sa.ForeignKeyConstraint(
            ["product_id"], ["store_product.id"], name=op.f("fk_store_branch_product_product_id_store_product")
        ),
        sa.PrimaryKeyConstraint("branch_id", "product_id", name=op.f("pk_store_branch_product")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("store_branch_product")
    with op.batch_alter_table("store_product", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_store_product_product_type_id"))
        batch_op.drop_index(batch_op.f("ix_store_product_category_id"))

    op.drop_table("store_product")
    with op.batch_alter_table("store_branch", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_store_branch_partner_id"))

    op.drop_table("store_branch")
    op.drop_table("roles_users")
    op.drop_table("user")
    op.drop_table("store_product_type")
    op.drop_table("store_category")
    op.drop_table("role")
    with op.batch_alter_table("merchants_payment", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_merchants_payment_status"))
        batch_op.drop_index(batch_op.f("ix_merchants_payment_integration_transaction"))
        batch_op.drop_index(batch_op.f("ix_merchants_payment_integration_slug"))

    op.drop_table("merchants_payment")
    op.drop_table("merchants_integrations")
    # ### end Alembic commands ###
