"""settings

Revision ID: f7dec9ce1ab9
Revises: 3d1fa949e7d8
Create Date: 2025-11-30 00:24:08.640348

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f7dec9ce1ab9"
down_revision = "3d1fa949e7d8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "store_settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("value", sa.JSON(), nullable=True),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("updated", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], name=op.f("fk_store_settings_user_id_user")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_store_settings")),
        sa.UniqueConstraint("slug", name=op.f("uq_store_settings_slug")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("store_settings")
    # ### end Alembic commands ###
