name: Build and Publish Docker Images

on:
  push:
    branches:
      - main
  release:
    types:
      - created

permissions:
  contents: read
  packages: write

jobs:
  test_and_build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]

      # - name: Run tests
      #   run: |
      #     pytest

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Define docker tags
        id: vars
        run: |
          if [[ "${{matrix.python-version}}" == "3.12" ]]; then
            echo "LATEST_TAG=latest" >> $GITHUB_ENV
          fi

      - name: Build and push Docker image to GitHub Container Registry
        if: github.event_name == 'push'
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/mariofix/flask-merchants:main-${{ matrix.python-version }}
            ${{ matrix.python-version == '3.12' && 'ghcr.io/mariofix/flask-merchants:latest' || ''}}

      - name: Build and push release Docker image to GitHub Container Registry
        if: github.event_name == 'release'
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/mariofix/flask-merchants:${{ github.event.release.tag_name }}
            ghcr.io/mariofix/flask-merchants:${{matrix.python-version}}
